// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MicroRabbit.Banking.Domain.Models;

[Keyless]
[Table("Account")]
public partial class Account
{
    [Column("id")]
    public long Id { get; set; }

    [StringLength(50)]
    public string AccountType { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal? AccountBalance { get; set; }
}